let words =    ["ISTANBUL",
                "ANKARA",
                "KAHRAMANMARAS",
                "DIYARBAKIR",
                "JAPONYA",
                "ISVICRE",
                "TURKIYE",
                "INGILTERE",
                "AVUSTRALYA",
                "KARADENIZ",
                "KAPLAN",
                "DAGASLANI",
                "AMERIKA",
                "AVRASYA",
                "KARADENIZ",
                "AKDENIZ"];